<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="en" sourcelanguage="">
<context>
    <name>timeUtils</name>
    <message>
        <location filename="../utils/timeUtils.py" line="18"/>
        <source>Timed Out</source>
        <translation>Timed Out</translation>
    </message>
    <message>
        <location filename="../utils/timeUtils.py" line="45"/>
        <source>Day</source>
        <translation>Day</translation>
    </message>
    <message>
        <location filename="../utils/timeUtils.py" line="47"/>
        <source>Days</source>
        <translation>Days</translation>
    </message>
    <message>
        <location filename="../utils/timeUtils.py" line="83"/>
        <source>error_get_cetus_time</source>
        <translation>Error duting calculation of time for Cetus</translation>
    </message>
    <message>
        <location filename="../utils/timeUtils.py" line="103"/>
        <source>error_get_fortuna_time</source>
        <translation>Error during calculation of time for Fortuna</translation>
    </message>
</context>
</TS>
